from time import sleep

sleep(1)
print("######   THIS   ######")
sleep(1)
print("######    IS    ######")
sleep(1)
print("######   SOME   ######")
sleep(1)
print("######   DOPE   ######")
sleep(1)
print("######  EXAMPLE ######")
sleep(1)
print("######   INNIT  ######")
sleep(1)
print("######   ????   ######")
sleep(1)
